### ISSUE TITLE
Unable to scroll with touch when disabled

### ISSUE THREAD

**Issue by desandro** [desandro/draggabilly#189]
From metafizzy/packery#474

Test case: https://codepen.io/desandro/pen/VLqzgQ
This is your codepen and it should scroll in mobile on unbinding events

**Comment by lothargrieb** [comment]
I would like to cautiously ask what the status is with this bug. Otherwise, I am very excited about the component in conjunction with Packery. Some users write that destroy and create would help with them, but this workaround has other errors.
An authoritative answer would be helpful, otherwise I would have to switch to another component.
