### ISSUE TITLE
Specify boundary in pixels

### ISSUE THREAD

**Issue by vkbansal** [desandro/draggabilly#62]
It would be great if there was an option to specify boundary in pixels
```javascript
boundary: {top: 0, bottom: 0, left: 0, right: 300px}
```

**Comment by desandro** [comment]
Closing this issue as it didn't get enough public interest. Alas! :ghost:

**Comment by davidchase** [comment]
@desandro i think this has some interest from different people, maybe im wrong #70 
in my situation some simple code:

```js
  if (this.position.x > someVar || this.position.x < otherVar){
     this.disable();
  }
```
so in this case dragging on the x-axis has a stop when users drags item too far left or too far right.
but gets tricky when i need to figure how to re-enable dragging once the user is back within range.

with something like an offsetLimit proposed in #70 or like proposed above there's a boundary setup by variables rather than a dom element such as the parent container

hopefully this makes sense, let me know.
